### ISSUE TITLE
Inverse probability weighting

### ISSUE THREAD

**Issue by aghaynes** [chjackson/flexsurv#171]
I came across your package this morning... it looks very nice. Some great features!

What type of weights do `flexsurvreg` and `flexsurvspline` expect. The documentation states "case weights", but this is a little vague... are they frequency weights, probability weights, ...? 

I'm intending to use your package for a inverse probability of censoring weighted analysis... is that possible?

I noticed that the weights do not seem to be restricted to be integer or >= 1...

Thanks in advance!

**Comment by chjackson** [comment]
Thanks for the report - yes the documentation is deficient here.   This is intended to be consistent with what base R modelling functions (`glm`, `lm`) and `survreg` do. The weights are used in model fitting - the fitted model is defined by maximising the weighted sum of the individual-specific log-likelihoods.  There's no restriction on their value, but they should be numeric. I don't have much experience with weighted analysis, but if your estimator is defined as the weighted maximum likelihood then you can do it in flexsurv.

**Comment by aghaynes** [comment]
Thanks! It seems to be OK and should work!
