### ISSUE TITLE
Manually changing coefficients in the 'fits' object in multistate model

### ISSUE THREAD

**Issue by mcincam100** [chjackson/flexsurv#174]
Hello,

I am trying to manually change the coefficient on a treatment variable within fits <- flexsurvreg_list(fits). I want to see how changing the effect of an (assumed to be randomly assigned) treatment changes the outcome of subsequent multistate simulations in hesim.  The reason I need to do this is because I don't actually have a treatment variable in my data. So, I am simulating one and randomly assigning it to cases, and then trying to add an assumed effect size for the hesim component to look at counterfactuals.

Here is a snippet:

# Create data frame
data <- data.frame(patient_id, Tstart, Tstop, status, trans, strategy_id, sex, education, employment, age)

# Write to CSV
write.csv(data, file = "J:/Data Development Unit/Administrative/Analytical Diversification/R Testing/flexsurvmod.csv", row.names = FALSE)

# Define your transition data
surv_dat <- read.csv("J:/Data Development Unit/Administrative/Analytical Diversification/R Testing/flexsurvmod.csv")

# Fit the survival models
fits <- vector(length = max(tmat, na.rm = TRUE), mode = "list")
for (i in 1:length(fits)){
 fits[[i]] <- flexsurvreg(Surv(Tstart, Tstop, status) ~ factor(strategy_id) + sex + education + employment + age,
                           data = surv_dat,
                           subset = (trans == i),
                           dist = "weibull")
}

fits <- flexsurvreg_list(fits)

# Get the index of the strategy_id coefficient
index <- which(rownames(fits[[1]]$results) == "factor(strategy_id)1")
 
# Change the coefficient
fits[[1]]$results[index, "est"] <- 1.5

This does not work. Apparently the 'fits' object is unable to be modified, correct? Are there any ways I could do this? 

Thanks, Cameron

**Comment by chjackson** [comment]
Closing due to no clear issue
