### ISSUE TITLE
Issue with covariate on scale parameter of Weibull ATF for weibull distribution

### ISSUE THREAD

**Issue by sbihorel** [chjackson/flexsurv#175]
Hi

While trying to fit a flexsurvreg model using a Weibull distribution and testing covariates on ancillary parameters, I stumbled what looks like a bug... Adding factor or character covariate on the scale parameter returns and error. Adding a numeric variable on scale does not. Since this is my first foray in parametric survival analysis, I'd like to know if I am doing things wrong or if there is indeed a bug

Reprex:
```
# Fitting a basic model works
fit1 <- flexsurvreg(Surv(recyrs, censrec) ~ group , data = bc, dist = 'weibull')
# Fitting the effect of group on shape works
fit2 <- flexsurvreg(Surv(recyrs, censrec) ~ group + shape(group), data = bc, dist = 'weibull')
# Fitting the effect of group on scale results in an error
fit3 <- flexsurvreg(Surv(recyrs, censrec) ~ group + scale(group), data = bc, dist = 'weibull')
# Fitting the effect of group on scale works
fit4 <- flexsurvreg(Surv(recyrs, censrec) ~ group + scale(rectime), data = bc, dist = 'weibull')
```

Thanks

**Comment by sbihorel** [comment]
Thanks for your feedback. That's really useful.

**Comment by chjackson** [comment]
A warning is now given in https://github.com/chjackson/flexsurv/commit/dd26c86391b6c9c69233383d857d09bc5ab56107
