### ISSUE TITLE
Relative Survival model no longer compatible with R versions < 4.2

### ISSUE THREAD

**Issue by mikesweeting** [chjackson/flexsurv#180]
I'm no longer able to run relative survival models on R versions < 4.2. Running on version 4.1 I get the following.

``` 
    bc$bh <- rep(0.01, nrow(bc))
    flexsurvreg(Surv(recyrs, censrec) ~ group, data=bc, dist="weibullPH", bhazard=bh)
```
Error in simplify2array(res, except = NULL) :
unused argument (except = NULL)

Is there a way of making the new dev version backward compatible?

**Comment by chjackson** [comment]
Thanks for spotting, I think https://github.com/chjackson/flexsurv/commit/7978e4cfa5bdbef05616385356fb5df9f4bc2c66 fixes this?
