### ISSUE TITLE
Sampling of parameters for incorporation with multiple imputation

### ISSUE THREAD

**Issue by jwb133** [chjackson/flexsurv#198]
Dear Chris

I am exploring using flexsurv to enable the [smcfcs](https://cran.r-project.org/package=smcfcs) package which does multiple imputation of covariates to impute based on flexible parametric models using flexsurvspline. For this I need to draw from the approximate multivariate normal posterior of the model parameters.

From the documentation for flexsurvreg and flexsurvspline, it seems res.t contains the MLEs on a scale for which parameters lie on the whole real line. But if I run flexsurvspline with k=0, giving a Weibull model, both res and res.t show the same values, and the gamma1 value is the shape parameter which must be positive. Indeed if I take the estimates from res (or res.t) and do +/- 1.96 times the SEs from res (or res.t) I get slightly different CI limits to the ones saved in res (and res.t), suggesting the inference is indeed being done on a transformed scale that I am not being given by res.t.

Sorry if (as is likely) I am making a stupid mistake here.

Best wishes
Jonathan

**Comment by jwb133** [comment]
Sorry I wrote too soon. I found you have a function normboot.flexsurvreg which draws from the asymptotic normal distribution of the MLEs / approximate posterior. I think I can use this, with raw=TRUE, to get a draw of the model parameters. And then if I modify a fitted model from flexsurvspline by overwriting the first column of the res.t component, then this modified fitted model will give me (via the summary function) estimates of survival/hazard using the newly drawn parameter values.

**Comment by chjackson** [comment]
Hi Jonathan,

That's an interesting point about the Royston-Parmar model (or the implementation of it in flexsurv).  $\gamma_0$ isn't constrained to be positive.  For $\gamma_0 > 0$ it does agree with the Weibull distribution with shape $\gamma_0$, but it also allows $\gamma_0<0$.  I think that's still a valid model, as long as the log cumulative hazard is a non-decreasing function of time.  (flexsurv only checks that implicitly during fitting, in that if a proposed set of coefficients gives zero likelihood for the data, then they are rejected).

Overwriting the model object will work as you say, though it's not documented!  Using functions like psurvspline, hsurvpsline (see the [reference](https://chjackson.github.io/flexsurv/reference/index.html#probability-distributions)) is "safer".  Though [`bootci.fmsm(...,sample=TRUE)`](https://chjackson.github.io/flexsurv/reference/bootci.fmsm.html) is a more direct route to get a sample of an arbitrary function of parameters.

**Comment by jwb133** [comment]
Thanks Chris. Regarding psurvspline, I can see that various arguments related to covariate effects have been removed, but I can't see what approach has replaced these to incorporate the covariate effects? For type="hazard" which is what I plan to use, I can manually calculate survival and cumulative hazard values given the values of these at covariates=0, but this is messier and more prone to me making an error. Am I missing something in the intended usage of psurvspline?

**Comment by chjackson** [comment]
These arguments were removed for consistency with functions like `pgamma`, `pweibull`, etc which don't expect to know how their parameters might be modified in regression models.    To summarise fitted models for particular covariate values, the official way is the `summary(..., newdata=)` method.  So to generate samples from the sampling distribution of summaries, you might use `bootci.fmsm(..., fn=..., newdata=, ci=FALSE)` with a `fn` based on the summary method, then any `newdata` argument will be passed through to the summary method.

**Comment by jwb133** [comment]
[please ignore if answering me is becoming tedious!]

Because of the way I sample missing covariates, I need to able to re-calculate predicted values of survival/hazard for the same parameter values, so I think I need to sample the parameter values myself first and then use summary(..., newdata=). I need the survival (and then hazard) for each individual in the dataset used to fit the model, at their corresponding observed time. I think summary(..., cross=FALSE) should do this:

```{r}
library(flexsurv)
set.seed(123)
myshape <- 1.5
myscale <- 3
n <- 50
x <- rnorm(n)
t <- rweibull(n=n,shape=myshape,scale=exp(x)^(-1/myshape))
c <- rexp(n)
delta <- 1*(t<c)
t[delta==0] <- c[delta==0]
mydata <- data.frame(x=x,t=t, delta=delta)
spl <- flexsurvspline(Surv(t,delta) ~ x, data=mydata, k=0, scale="hazard")
# create estimates of survival for each individual at their individual time, using cross=FALSE
mysummary <- summary(object=spl, newdata=mydata, type="survival", ci=FALSE, t=t, cross=FALSE)
```

but this gives the warning:
```{r}
Warning message:
In split.default(x = seq_len(nrow(x)), f = f, drop = drop, ...) :
  data length is not a multiple of split variable
```

Am I doing something wrong?

Continued thanks.

**Comment by chjackson** [comment]
Sorry, this is a bug, which I think is now fixed in https://github.com/chjackson/flexsurv/commit/eb7e61bff4f057ada332ec9606e67f0afbf43be3 .  Though the version you have will work properly with `summary(..., cross=FALSE, tidy=TRUE)`.
