### ISSUE TITLE
Opposite Coefficients for Exponential AFT Model

### ISSUE THREAD

**Issue by JaneSweets** [chjackson/flexsurv#201]
Hi -

Very nice package first of all!

As I am conducting analysis using AFT models under different distribution assumptions, I have noticed that with the same formula, the option dist="exp" would yield exactly opposite coefficients compared with other dist options, as shown below. The example is conducted using the veteran dataset in survival package.
![image](https://github.com/user-attachments/assets/3d8970c7-0b48-4fe3-9af1-642238767fbb)
![image](https://github.com/user-attachments/assets/c8665df5-29bb-458e-aad3-a03b2f0eb12a)

I am not sure if this is a consistent issue. Please let me know if I misunderstood anything.

Thanks.

**Comment by chjackson** [comment]
For the benefit of anyone finding this question by Google, the answer is that the coefficients may have different meanings depending on the distribution - as explained in the [distributions vignette](https://cran.r-project.org/web/packages/flexsurv/vignettes/distributions.pdf) and [help(flexsurvreg)](https://chjackson.github.io/flexsurv/reference/flexsurvreg.html) argument `"dist"`.
