### ISSUE TITLE
Warnings during model fitting

### ISSUE THREAD

**Issue by chjackson** [chjackson/flexsurv#91]
Occasionally flexsurvreg will print a warning "NaNs produced" while fitting a model.  This can result from evaluating the "p" or "d" function for a distribution when parameters visited during optimisation are on the boundary of the parameter space.   This is confusing to users, so should be guarded against somehow. 

Not sure about using `suppressWarnings`.  This might get rid of helpful warnings. 

Instead, flexsurvreg could detect parameters that are on the boundary of the parameter space before calling these functions.  Then what to do?  Could return a likelihood of zero, which will force the optimiser to move on.  But that might misrepresent the behaviour of the likelihood near the boundary.  Or it could assume smoothness, and replace, e.g. a zero rate with a small number `.Machine$double.eps`?

**Comment by chjackson** [comment]
In 8bb7c96 this now silences all warnings matching "NaNs produced" from calling PDF and CDF functions while evaluating the likelihood.  I'll leave this issue open, in case anyone familiar with this kind of problem has a better suggestion.

**Comment by anniekellner** [comment]
Using ```method = Nelder-Mead``` helped me reduce the warnings and gave me slightly better estimates
